import * as i0 from '@angular/core';
import { Component } from '@angular/core';
import * as i1 from '@angular/cdk/accordion';
import { CdkAccordionModule } from '@angular/cdk/accordion';

/**
 * @title Accordion overview
 */
class CdkAccordionOverviewExample {
    constructor() {
        this.items = ['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5'];
        this.expandedIndex = 0;
    }
    static { this.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "17.0.4", ngImport: i0, type: CdkAccordionOverviewExample, deps: [], target: i0.ɵɵFactoryTarget.Component }); }
    static { this.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.0.0", version: "17.0.4", type: CdkAccordionOverviewExample, isStandalone: true, selector: "cdk-accordion-overview-example", ngImport: i0, template: "<cdk-accordion class=\"example-accordion\">\r\n  @for (item of items; track item; let index = $index) {\r\n    <cdk-accordion-item\r\n\r\n      #accordionItem=\"cdkAccordionItem\"\r\n      class=\"example-accordion-item\"\r\n      role=\"button\"\r\n      tabindex=\"0\"\r\n      [attr.id]=\"'accordion-header-' + index\"\r\n      [attr.aria-expanded]=\"accordionItem.expanded\"\r\n      [attr.aria-controls]=\"'accordion-body-' + index\">\r\n      <div class=\"example-accordion-item-header\" (click)=\"accordionItem.toggle()\">\r\n        {{ item }}\r\n        <span class=\"example-accordion-item-description\">\r\n          Click to {{ accordionItem.expanded ? 'close' : 'open' }}\r\n        </span>\r\n      </div>\r\n      <div\r\n        class=\"example-accordion-item-body\"\r\n        role=\"region\"\r\n        [style.display]=\"accordionItem.expanded ? '' : 'none'\"\r\n        [attr.id]=\"'accordion-body-' + index\"\r\n        [attr.aria-labelledby]=\"'accordion-header-' + index\">\r\n        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis\r\n        excepturi incidunt ipsum deleniti labore, tempore non nam doloribus blanditiis\r\n        veritatis illo autem iure aliquid ullam rem tenetur deserunt velit culpa?\r\n      </div>\r\n    </cdk-accordion-item>\r\n  }\r\n</cdk-accordion>\r\n\r\n", styles: [".example-accordion {\r\n  display: block;\r\n  max-width: 500px;\r\n}\r\n\r\n.example-accordion-item {\r\n  display: block;\r\n  border: solid 1px #ccc;\r\n}\r\n\r\n.example-accordion-item + .example-accordion-item {\r\n  border-top: none;\r\n}\r\n\r\n.example-accordion-item-header {\r\n  display: flex;\r\n  align-content: center;\r\n  justify-content: space-between;\r\n}\r\n\r\n.example-accordion-item-description {\r\n  font-size: 0.85em;\r\n  color: #999;\r\n}\r\n\r\n.example-accordion-item-header,\r\n.example-accordion-item-body {\r\n  padding: 16px;\r\n}\r\n\r\n.example-accordion-item-header:hover {\r\n  cursor: pointer;\r\n  background-color: #eee;\r\n}\r\n\r\n.example-accordion-item:first-child {\r\n  border-top-left-radius: 4px;\r\n  border-top-right-radius: 4px;\r\n}\r\n\r\n.example-accordion-item:last-child {\r\n  border-bottom-left-radius: 4px;\r\n  border-bottom-right-radius: 4px;\r\n}\r\n"], dependencies: [{ kind: "ngmodule", type: CdkAccordionModule }, { kind: "directive", type: i1.CdkAccordion, selector: "cdk-accordion, [cdkAccordion]", inputs: ["multi"], exportAs: ["cdkAccordion"] }, { kind: "directive", type: i1.CdkAccordionItem, selector: "cdk-accordion-item, [cdkAccordionItem]", inputs: ["expanded", "disabled"], outputs: ["closed", "opened", "destroyed", "expandedChange"], exportAs: ["cdkAccordionItem"] }] }); }
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "17.0.4", ngImport: i0, type: CdkAccordionOverviewExample, decorators: [{
            type: Component,
            args: [{ selector: 'cdk-accordion-overview-example', standalone: true, imports: [CdkAccordionModule], template: "<cdk-accordion class=\"example-accordion\">\r\n  @for (item of items; track item; let index = $index) {\r\n    <cdk-accordion-item\r\n\r\n      #accordionItem=\"cdkAccordionItem\"\r\n      class=\"example-accordion-item\"\r\n      role=\"button\"\r\n      tabindex=\"0\"\r\n      [attr.id]=\"'accordion-header-' + index\"\r\n      [attr.aria-expanded]=\"accordionItem.expanded\"\r\n      [attr.aria-controls]=\"'accordion-body-' + index\">\r\n      <div class=\"example-accordion-item-header\" (click)=\"accordionItem.toggle()\">\r\n        {{ item }}\r\n        <span class=\"example-accordion-item-description\">\r\n          Click to {{ accordionItem.expanded ? 'close' : 'open' }}\r\n        </span>\r\n      </div>\r\n      <div\r\n        class=\"example-accordion-item-body\"\r\n        role=\"region\"\r\n        [style.display]=\"accordionItem.expanded ? '' : 'none'\"\r\n        [attr.id]=\"'accordion-body-' + index\"\r\n        [attr.aria-labelledby]=\"'accordion-header-' + index\">\r\n        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis\r\n        excepturi incidunt ipsum deleniti labore, tempore non nam doloribus blanditiis\r\n        veritatis illo autem iure aliquid ullam rem tenetur deserunt velit culpa?\r\n      </div>\r\n    </cdk-accordion-item>\r\n  }\r\n</cdk-accordion>\r\n\r\n", styles: [".example-accordion {\r\n  display: block;\r\n  max-width: 500px;\r\n}\r\n\r\n.example-accordion-item {\r\n  display: block;\r\n  border: solid 1px #ccc;\r\n}\r\n\r\n.example-accordion-item + .example-accordion-item {\r\n  border-top: none;\r\n}\r\n\r\n.example-accordion-item-header {\r\n  display: flex;\r\n  align-content: center;\r\n  justify-content: space-between;\r\n}\r\n\r\n.example-accordion-item-description {\r\n  font-size: 0.85em;\r\n  color: #999;\r\n}\r\n\r\n.example-accordion-item-header,\r\n.example-accordion-item-body {\r\n  padding: 16px;\r\n}\r\n\r\n.example-accordion-item-header:hover {\r\n  cursor: pointer;\r\n  background-color: #eee;\r\n}\r\n\r\n.example-accordion-item:first-child {\r\n  border-top-left-radius: 4px;\r\n  border-top-right-radius: 4px;\r\n}\r\n\r\n.example-accordion-item:last-child {\r\n  border-bottom-left-radius: 4px;\r\n  border-bottom-right-radius: 4px;\r\n}\r\n"] }]
        }] });

/**
 * Generated bundle index. Do not edit.
 */

export { CdkAccordionOverviewExample };
//# sourceMappingURL=accordion.mjs.map
